apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: your-node-image:latest
          env:
            - name: APP_LOCAL_PATH
              value: "sources"
            - name: APP_CONTAINER_PATH
              value: "/var/www/sources"
          volumeMounts:
            - name: app-sources
              mountPath: /var/www/sources
      volumes:
        - name: app-sources
          hostPath:
            path: /path/to/your/sources
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP