apiVersion: kustomize.config.k8s.io/v1beta1
kind: "Production Build"
resources:
  - app/environments/k8s_nginx_env.yml
  - app/environments/k8s_postgres_env.yml
  - app/jobs/k8s_created_database_postgres_job.yml # job postgres
  - app/environments/k8s_mongo_env.yml
  - app/jobs/k8s_created_collection_mongo_job.yml # job mongo
  - app/environments/k8s_rabbitmq_env.yml
  - app/environments/k8s_phpfpm_env.yml
  - app/environments/k8s_node_env.yml
  - app/jobs/k8s_building_frontend_job.yml # job mongo
