apiVersion: batch/v1
kind: Job
metadata:
  name: create-collection-job
spec:
  template:
    spec:
      containers:
        - name: create-collection
          image: mongo:latest
          command: ['sh', '-c', 'mongosh --host mongodb-service --authenticationDatabase admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --eval "db.getSiblingDB(\'logs\').createCollection(\'your_collection_name\')"']
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "m_raptor"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "m_lama22"
      restartPolicy: Never