apiVersion: batch/v1
kind: Job
metadata:
  name: create-database-job
spec:
  template:
    spec:
      containers:
        - name: create-database
          image: postgres:latest
          command: ['sh', '-c', 'psql -h postgres-service -U postgres -c "CREATE DATABASE sport_experts_db;"']
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "your-postgres-password"
      restartPolicy: Never
